### ISSUE TITLE
Errors when I run this plugin.

### ISSUE THREAD

**Issue by jimi1104** [KPGTB/KKthirst#5]
[16:10:47 INFO]: [KThirst] Enabling KThirst v2.2.6-SNAPSHOT
[16:10:47 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.IllegalArgumentException: Newer version! Server downgrades are not supported!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.getMaterial(CraftMagicNumbers.java:260) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:521) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1813) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1762) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:540) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:498) ~[?:?]
        at com.github.kpgtb.ktools.util.item.ItemUtil.deserializeItem(ItemUtil.java:153) ~[KTools-min-2.4.5-SNAPSHOT.jar:?]
        at pl.kpgtb.kthirst.data.persister.ItemsPersister.lambda$sqlArgToJava$1(ItemsPersister.java:52) ~[KThirst-2.2.6-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at pl.kpgtb.kthirst.data.persister.ItemsPersister.sqlArgToJava(ItemsPersister.java:47) ~[KThirst-2.2.6-SNAPSHOT.jar:?]
        at com.j256.ormlite.field.BaseFieldConverter.resultToJava(BaseFieldConverter.java:30) ~[?:?]
        at com.j256.ormlite.field.FieldType.resultToJava(FieldType.java:863) ~[?:?]
        at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:62) ~[?:?]
        at com.j256.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:290) ~[?:?]
        at com.j256.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:163) ~[?:?]
        at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:207) ~[?:?]
        at com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:127) ~[?:?]
        at com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:251) ~[?:?]
        at pl.kpgtb.kthirst.manager.machine.MachineManager.loadPlacedMachines(MachineManager.java:99) ~[KThirst-2.2.6-SNAPSHOT.jar:?]
        at pl.kpgtb.kthirst.KThirst.onEnable(KThirst.java:145) ~[KThirst-2.2.6-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:660) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:571) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:622) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:421) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1106) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"f01d66d"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:10:47 WARN]: java.lang.RuntimeException: java.io.IOException: Failed to deserialize object
[16:10:47 WARN]:        at KThirst-2.2.6-SNAPSHOT.jar//pl.kpgtb.kthirst.data.persister.ItemsPersister.lambda$sqlArgToJava$1(ItemsPersister.java:54)
[16:10:47 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[16:10:47 WARN]:        at KThirst-2.2.6-SNAPSHOT.jar//pl.kpgtb.kthirst.data.persister.ItemsPersister.sqlArgToJava(ItemsPersister.java:47)
[16:10:47 WARN]:        at com.j256.ormlite.field.BaseFieldConverter.resultToJava(BaseFieldConverter.java:30)
[16:10:47 WARN]:        at com.j256.ormlite.field.FieldType.resultToJava(FieldType.java:863)
[16:10:47 WARN]:        at com.j256.ormlite.stmt.mapped.BaseMappedQuery.mapRow(BaseMappedQuery.java:62)
[16:10:47 WARN]:        at com.j256.ormlite.stmt.SelectIterator.getCurrent(SelectIterator.java:290)
[16:10:47 WARN]:        at com.j256.ormlite.stmt.SelectIterator.nextThrow(SelectIterator.java:163)
[16:10:47 WARN]:        at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:207)
[16:10:47 WARN]:        at com.j256.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:127)
[16:10:47 WARN]:        at com.j256.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:251)
[16:10:47 WARN]:        at KThirst-2.2.6-SNAPSHOT.jar//pl.kpgtb.kthirst.manager.machine.MachineManager.loadPlacedMachines(MachineManager.java:99)
[16:10:47 WARN]:        at KThirst-2.2.6-SNAPSHOT.jar//pl.kpgtb.kthirst.KThirst.onEnable(KThirst.java:145)
[16:10:47 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[16:10:47 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[16:10:47 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[16:10:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506)
[16:10:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:660)
[16:10:47 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:571)
[16:10:47 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:622)
[16:10:47 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:421)
[16:10:47 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[16:10:47 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
[16:10:47 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:10:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[16:10:47 WARN]: Caused by: java.io.IOException: Failed to deserialize object
[16:10:47 WARN]:        at org.bukkit.util.io.BukkitObjectInputStream.newIOException(BukkitObjectInputStream.java:59)
[16:10:47 WARN]:        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:51)
[16:10:47 WARN]:        at java.base/java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1813)
[16:10:47 WARN]:        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1762)
[16:10:47 WARN]:        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:540)
[16:10:47 WARN]:        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:498)
[16:10:47 WARN]:        at KTools-min-2.4.5-SNAPSHOT.jar//com.github.kpgtb.ktools.util.item.ItemUtil.deserializeItem(ItemUtil.java:153)
[16:10:47 WARN]:        at KThirst-2.2.6-SNAPSHOT.jar//pl.kpgtb.kthirst.data.persister.ItemsPersister.lambda$sqlArgToJava$1(ItemsPersister.java:52)
[16:10:47 WARN]:        ... 24 more
[16:10:47 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(java.util.Map)" is null
[16:10:47 WARN]:        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:49)
[16:10:47 WARN]:        ... 30 more

**Comment by KPGTB** [comment]
Hey! Sorry for late 😅This issue is caused by downgrading server version. I can't help you. To fix this issue, you need to go to database (plugins/KTools/database.db OR mysql which you configured) and remove all placed machines
